use axum::{
    extract::{Path, Query, State},
    routing::{get, patch, post},
    Extension, Json, Router,
};
use chrono::Utc;
use serde::{Deserialize, Serialize};
use validator::Validate;

use crate::{
    error::{ApiError, ApiResult},
    models::{
        Evidence, EvidenceResponse, EvidenceType, HarmRisk, MediaAsset, Report, ReportStatus,
        TranscodingStatus, UploadEvidenceRequest, User, VisibilityTier,
    },
    services::surrealdb_features::{FullTextSearchService, GraphQueryService, SearchResult},
    AppState,
};

pub fn public_router() -> Router<AppState> {
    Router::new()
        .route("/", post(create_report))
        .route("/search", get(search_reports))
        .route("/:id", get(get_report))
        .route("/:id", patch(update_report_status))
        .route("/:id/connections", get(get_report_connections))
        .route("/:id/evidence", post(upload_evidence))
        .route("/:id/evidence", get(list_evidence))
}

#[derive(Debug, Deserialize)]
struct SearchQuery {
    q: String,
    #[serde(default = "default_limit")]
    limit: i32,
}

fn default_limit() -> i32 {
    20
}

#[derive(Debug, Serialize)]
struct SearchResponse {
    results: Vec<SearchResult>,
    total: usize,
}

#[derive(Debug, Deserialize, Validate)]
struct CreateReportRequest {
    #[validate(length(min = 5, max = 200))]
    title: String,
    #[validate(length(min = 10))]
    description: String,
    category: String,
    incident_date: Option<chrono::DateTime<Utc>>,
    street_name: Option<String>,
    city: Option<String>,
    postcode_district: Option<String>,
    visibility_tier: VisibilityTier,
    harm_risk: HarmRisk,
    source_refs: Vec<String>,
}

#[derive(Debug, Deserialize)]
struct UpdateReportStatusRequest {
    status: ReportStatus,
}

#[derive(Debug, Serialize)]
struct ReportResponse {
    report: Report,
}

/// Full-text search across reports using SurrealDB native search
async fn search_reports(
    State(state): State<AppState>,
    Query(params): Query<SearchQuery>,
) -> ApiResult<Json<SearchResponse>> {
    let search_service = FullTextSearchService::new(state.db.clone());

    let results = search_service
        .search_reports(params.q.clone(), params.limit)
        .await?;

    let total = results.len();

    tracing::info!(
        "Full-text search for '{}' returned {} results",
        params.q,
        total
    );

    Ok(Json(SearchResponse { results, total }))
}

/// Get report connections using graph queries
async fn get_report_connections(
    State(state): State<AppState>,
    Path(id): Path<String>,
) -> ApiResult<Json<serde_json::Value>> {
    let graph_service = GraphQueryService::new(state.db.clone());

    let connections = graph_service
        .find_connected_reports(id)
        .await?;

    Ok(Json(serde_json::to_value(connections).unwrap()))
}

/// Create a new report with RLAC validation
/// User must be authenticated to create reports
async fn create_report(
    State(state): State<AppState>,
    user: Option<Extension<User>>,
    Json(payload): Json<CreateReportRequest>,
) -> ApiResult<Json<ReportResponse>> {
    // Validate request
    payload
        .validate()
        .map_err(|e| ApiError::Validation(e.to_string()))?;

    // Extract authenticated user from middleware (optional for create)
    let user = user.map(|Extension(u)| u);

    let now = Utc::now();
    let submitted_by = user.as_ref().and_then(|u| u.id.clone());

    // Create report object
    let report = Report {
        id: None, // Will be generated by SurrealDB
        title: payload.title,
        description: payload.description,
        category: payload.category,
        incident_date: payload.incident_date,
        street_name: payload.street_name,
        city: payload.city,
        postcode_district: payload.postcode_district,
        status: if submitted_by.is_some() {
            ReportStatus::Submitted
        } else {
            ReportStatus::Draft
        },
        visibility_tier: payload.visibility_tier,
        harm_risk: payload.harm_risk,
        source_refs: payload.source_refs,
        submitted_by: submitted_by.clone(),
        submitted_at: if submitted_by.is_some() {
            Some(now)
        } else {
            None
        },
        created_at: now,
        updated_at: now,
    };

    // Create report in database - RLAC will enforce permissions
    let created: Option<Report> = state
        .db
        .create("report", report)
        .await
        .map_err(|e| {
            tracing::error!("Failed to create report: {}", e);
            ApiError::Internal(anyhow::anyhow!("Failed to create report"))
        })?;

    let report = created.ok_or_else(|| {
        ApiError::Internal(anyhow::anyhow!("Report created but not returned"))
    })?;

    tracing::info!(
        "Report created: {} by user {:?}",
        report.id.as_ref().unwrap_or(&"unknown".to_string()),
        submitted_by
    );

    Ok(Json(ReportResponse { report }))
}

/// Get a report by ID with RLAC filtering
/// Public reports visible to all, private reports only to submitter/reviewers
async fn get_report(
    State(state): State<AppState>,
    Path(id): Path<String>,
    _user: Option<Extension<User>>,
) -> ApiResult<Json<ReportResponse>> {
    // User is extracted by middleware if authenticated (optional for public reports)

    // Fetch report - RLAC will filter based on $auth context
    // If user is not authenticated, only public reports are returned
    let reports: Vec<Report> = state
        .db
        .select(&format!("report:{}", id))
        .await
        .map_err(|e| {
            tracing::error!("Failed to fetch report: {}", e);
            ApiError::Internal(anyhow::anyhow!("Failed to fetch report"))
        })?;

    let report = reports
        .into_iter()
        .next()
        .ok_or_else(|| ApiError::NotFound("Report not found or access denied".to_string()))?;

    Ok(Json(ReportResponse { report }))
}

/// Update report status (requires reviewer or admin role)
async fn update_report_status(
    State(state): State<AppState>,
    Extension(user): Extension<User>,
    Path(id): Path<String>,
    Json(payload): Json<UpdateReportStatusRequest>,
) -> ApiResult<Json<ReportResponse>> {

    // Check if user has permission to update reports
    if !user.roles.contains(&"reviewer".to_string())
        && !user.roles.contains(&"admin".to_string())
    {
        return Err(ApiError::Authorization(
            "Updating report status requires reviewer or admin role".to_string(),
        ));
    }

    // Update report status - RLAC will enforce permissions
    let update_query = format!(
        "UPDATE report:{} SET status = $status, updated_at = time::now() RETURN AFTER",
        id
    );

    let updated: Vec<Report> = state
        .db
        .client
        .query(&update_query)
        .bind(("status", serde_json::to_value(&payload.status).unwrap()))
        .await
        .map_err(|e| {
            tracing::error!("Failed to update report: {}", e);
            ApiError::Internal(anyhow::anyhow!("Failed to update report"))
        })?
        .take(0)
        .map_err(|e| {
            tracing::error!("Failed to parse updated report: {}", e);
            ApiError::Internal(anyhow::anyhow!("Failed to parse updated report"))
        })?;

    let report = updated
        .into_iter()
        .next()
        .ok_or_else(|| ApiError::NotFound("Report not found or access denied".to_string()))?;

    tracing::info!(
        "Report {} status updated to {:?} by user {}",
        id,
        payload.status,
        user.username
    );

    Ok(Json(ReportResponse { report }))
}

/// Upload evidence for a report (images, documents, or video metadata)
/// For large files (videos), returns a presigned upload URL
async fn upload_evidence(
    State(state): State<AppState>,
    Extension(user): Extension<User>,
    Path(report_id): Path<String>,
    Json(payload): Json<UploadEvidenceRequest>,
) -> ApiResult<Json<EvidenceResponse>> {
    // Validate request
    payload
        .validate()
        .map_err(|e| ApiError::Validation(e.to_string()))?;

    // Parse evidence type
    let evidence_type = match payload.evidence_type.to_lowercase().as_str() {
        "video" => EvidenceType::Video,
        "image" => EvidenceType::Image,
        "document" => EvidenceType::Document,
        "testimony" => EvidenceType::Testimony,
        "other" => EvidenceType::Other,
        _ => {
            return Err(ApiError::Validation(
                "Invalid evidence type. Must be: video, image, document, testimony, or other"
                    .to_string(),
            ))
        }
    };

    let user_id = user.id.clone().unwrap_or_else(|| "unknown".to_string());
    let now = Utc::now();

    // Handle media asset creation if file data is provided
    let media_asset_id = if let Some(file_base64) = &payload.file_base64 {
        // Decode base64 file data
        let file_data = base64::Engine::decode(
            &base64::engine::general_purpose::STANDARD,
            file_base64,
        )
        .map_err(|e| {
            ApiError::Validation(format!("Invalid base64 file data: {}", e))
        })?;

        let file_size_bytes = file_data.len() as i64;
        let filename = payload.filename.clone().unwrap_or_else(|| {
            format!("evidence_{}.bin", chrono::Utc::now().timestamp())
        });

        // Calculate SHA256 checksum
        use sha2::{Digest, Sha256};
        let mut hasher = Sha256::new();
        hasher.update(&file_data);
        let checksum = format!("{:x}", hasher.finalize());

        // Determine MIME type (basic detection)
        let mime_type = mime_guess::from_path(&filename)
            .first_or_octet_stream()
            .to_string();

        // For now, store as placeholder path
        // TODO: Implement actual object storage (S3/MinIO) integration
        let storage_path = format!("evidence/{}/{}", report_id, filename);

        // Create media asset
        let media_asset = MediaAsset {
            id: None,
            filename: filename.clone(),
            mime_type,
            file_size_bytes,
            storage_path: storage_path.clone(),
            storage_url: None,
            thumbnail_url: None,
            preview_url: None,
            duration_seconds: None,
            width: None,
            height: None,
            transcoding_status: TranscodingStatus::Pending,
            checksum_sha256: checksum,
            uploaded_by: Some(user_id.clone()),
            uploaded_at: now,
            processed_at: None,
        };

        let created_asset: Option<MediaAsset> = state
            .db
            .create("media_asset", media_asset)
            .await
            .map_err(|e| {
                tracing::error!("Failed to create media asset: {}", e);
                ApiError::Internal(anyhow::anyhow!("Failed to create media asset"))
            })?;

        let asset = created_asset.ok_or_else(|| {
            ApiError::Internal(anyhow::anyhow!("Media asset created but not returned"))
        })?;

        tracing::info!(
            "Media asset created: {} for report {}",
            asset.id.as_ref().unwrap_or(&"unknown".to_string()),
            report_id
        );

        asset.id
    } else {
        None
    };

    // Create evidence record
    let evidence = Evidence {
        id: None,
        report_id: format!("report:{}", report_id),
        media_asset_id: media_asset_id.map(|id| format!("media_asset:{}", id)),
        evidence_type,
        description: payload.description,
        collected_at: payload.collected_at,
        chain_of_custody: vec![],
        sealed: false,
        sealed_at: None,
        sealed_by: None,
        submitted_by: Some(user_id.clone()),
        created_at: now,
        updated_at: now,
    };

    let created_evidence: Option<Evidence> = state
        .db
        .create("evidence", evidence)
        .await
        .map_err(|e| {
            tracing::error!("Failed to create evidence: {}", e);
            ApiError::Internal(anyhow::anyhow!("Failed to create evidence"))
        })?;

    let evidence = created_evidence.ok_or_else(|| {
        ApiError::Internal(anyhow::anyhow!("Evidence created but not returned"))
    })?;

    tracing::info!(
        "Evidence created: {} for report {} by user {}",
        evidence.id.as_ref().unwrap_or(&"unknown".to_string()),
        report_id,
        user.username
    );

    // For video uploads, would return a presigned S3 URL here
    // TODO: Implement presigned URL generation for large file uploads
    let upload_url = None;

    Ok(Json(EvidenceResponse {
        evidence,
        upload_url,
    }))
}

/// List all evidence for a report
async fn list_evidence(
    State(state): State<AppState>,
    Path(report_id): Path<String>,
    _user: Option<Extension<User>>,
) -> ApiResult<Json<serde_json::Value>> {
    // Query all evidence for the report
    let query = format!(
        "SELECT * FROM evidence WHERE report_id = report:{} ORDER BY created_at DESC",
        report_id
    );

    let mut result = state.db.client.query(&query).await.map_err(|e| {
        tracing::error!("Failed to fetch evidence: {}", e);
        ApiError::Internal(anyhow::anyhow!("Failed to fetch evidence"))
    })?;

    let evidence: Vec<Evidence> = result.take(0).map_err(|e| {
        tracing::error!("Failed to parse evidence: {}", e);
        ApiError::Internal(anyhow::anyhow!("Failed to parse evidence"))
    })?;

    Ok(Json(serde_json::json!({
        "evidence": evidence,
        "total": evidence.len()
    })))
}
